development:
  adapter: postgresql
  host: db
  database: surrey_subs
  username: postgres
  password: password1234

test:
  adapter: postgresql
  host: db
  database: surrey_subs
  username: postgres
  password: password1234

